#
##oAuth2 configuration
#okta:
#  oauth2:
#    issuer: https://dev-14250978.okta.com/oauth2/default
#    client-id:  0oau3ipclIl15osxv5d6
#    client-secret: kydl6e3yPWO-rSmmIwvYfBycANVWt8Ueyda73SPJ
#
## Circuit Breaker Pattern configuration
#resilience4j:
#  circuitbreaker:
#    instances:
#      rate-service:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        waitDurationInOpenState: 5s
#        slidingWindowType: COUNT_BASED
#
## Circuit Breaker Pattern - retry configuration
#resilience4j.retry:
#  instances:
#    rate-service:
#      maxRetryAttempts: 3
#      waitDuration: 11000
#
### health endpoint
#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: health
#  endpoint:
#    health:
#      show-details: always
#
#spring:
#    application:
#      name: RATE-SERVICE
##eureka:
##    client:
##      register-with-eureka: true
##      fetch-registry: true
##      service-url:
##        defaultZone: http://localhost:8761/eureka/
##    instance:
##      hostname: localhost
#server:
#  port: 9091
#  servlet:
#    context-path: /rate-management
#
#eureka:
#  client:
#    register-with-eureka: false